# Generated by Django 5.1.3 on 2025-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_ingridents', models.CharField(max_length=100)),
                ('recipe_description', models.TextField(max_length=400)),
                ('instructions', models.TextField(default=None)),
                ('cooking_time', models.TextField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
