# Generated by Django 5.1.3 on 2025-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_ingridents',
            new_name='recipe_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.CharField(default='jess', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
