# Generated by Django 5.1.3 on 2025-04-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.CharField(max_length=400),
        ),
    ]
