# Generated by Django 5.1.3 on 2025-04-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
